### ISSUE TITLE
Ignore Archive and Trash

### ISSUE THREAD

**Issue by clementrsu** [bjrnt/alfred-bear#34]
Is there a way to ignore the Archive and / or Trash folder when searching for a note.

If  you have a note Todo in Notes, Archive and Trash then search pops up 3 results with no way to distinguish which one is the current one.

**Comment by bjrnt** [comment]
Thanks for calling this out! Fixed in https://github.com/bjrnt/alfred-bear/releases/tag/v3.1. :)
