### ISSUE TITLE
Error: there's no app set to open URL <callback>

### ISSUE THREAD

**Issue by ryan6416** [bjrnt/alfred-bear#7]
I downloaded and installed the latest release. I set the BEAR_TOKEN properly as the work env variable. When I search Bear Notes, I'm getting below error:

<img width="579" alt="Screen Shot 2020-02-05 at 5 02 29 PM" src="https://user-images.githubusercontent.com/12979345/73897050-9ea26500-4839-11ea-8e77-ef20179993e8.png">

Bear version: 1.7.8 (8306)
MacBook version: 10.15.3 MacOS Catalina
Alfred version: 4.0.8

**Comment by sa9sha9** [comment]
I faced a same error.

To solve it, open the Alfred workflow from Alfred settings, and opening this workflow setting. Then adding single quotes (or double quotes whichever) to x-callback-url text like bellow. 
<img width="1292" alt="スクリーンショット 2020-02-26 14 03 55" src="https://user-images.githubusercontent.com/14252323/75314071-0597c480-58a2-11ea-8d6f-a52177a7890d.png">

Then showing an another popup to ask opening 'xcall.app' and  click 'open'. 
<img width="614" alt="スクリーンショット 2020-02-26 14 00 04" src="https://user-images.githubusercontent.com/14252323/75314128-34ae3600-58a2-11ea-8d34-f79274b596a1.png">

Finally you can use Bear Search in alfred
<img width="1131" alt="スクリーンショット 2020-02-26 14 13 10" src="https://user-images.githubusercontent.com/14252323/75314140-4099f800-58a2-11ea-8024-b6f5f678e169.png">



But i think.. it's not useful for searching bear notes. If you want search bear notes, you should set a hotkey to open bear, and you can search in bear side bar. It's faster than using this workflow 😎

**Comment by bjrnt** [comment]
@sa9sha9 Thank you for the fix! :) I wasn't able to reproduce the problem on my own computer. I've uploaded an updated version with the fix in it.

I agree that it's faster to open Bear to search notes since Bear has to be open to use xcallbackurl, but I think it's useful for people who prefer to do all of their searches through Alfred.
