### ISSUE TITLE
Stuck on "Searching..."

### ISSUE THREAD

**Issue by jaimem88** [bjrnt/alfred-bear#8]
Stuck on "Searching..."

I've added my token from the Bear app. I've also allowed the `./alfred-bear` binary to run but no luck.

<img width="575" alt="Screen Shot 2020-03-02 at 3 30 38 pm" src="https://user-images.githubusercontent.com/11710811/75645680-fe562980-5c9a-11ea-890a-24a9bf19a9fe.png">

If the Bear app is open I can see the search happening on it but Alfred just stays on searching

**Comment by bjrnt** [comment]
@jaimem88 I think it was due the dependency on `xcall` to handle communication with Alfred. I rewrote the extension to access Alfred's SQLite DB directly (readonly though so no risk of data loss), and it should now be working much better. Would you give it another try?

**Comment by jaimem88** [comment]
Thanks @bjrnt [v3.0.0](https://github.com/bjrnt/alfred-bear/releases/tag/v3.0) is working like a charm! 🚀

**Comment by ghost** [comment]
I'm stuck at ”searching” too. **Catalina** 10.15.4 (up to date). **alfred-bear** 2.0.0 (up to date). I added the security permissions for alfred-bear to work under Catalina.

**Comment by bjrnt** [comment]
@Forrestus could you please try upgrading to [version 3.0](https://github.com/bjrnt/alfred-bear/releases/tag/v3.0) and see if the problem persists?

**Comment by ghost** [comment]
Thank you. It works. I was somehow convinced 2.0.0 is the latest version.
