### ISSUE TITLE
No application set to open URL

### ISSUE THREAD

**Issue by dodalovic** [bjrnt/alfred-bear#9]
Latest MacOS
Latest Bear

![image](https://user-images.githubusercontent.com/6358061/75759136-5fcad680-5d35-11ea-8bab-c959d6f4ce3d.png)

**Comment by bjrnt** [comment]
Thanks for reporting! Can you confirm that the fix suggested in #7 doesn't fix it? I think it may be due to xcall.app not being allowed to run

**Comment by bjrnt** [comment]
@dodalovic I rewrote the workflow to no longer use xcall. Would you give it another try? :)

**Comment by dodalovic** [comment]
Works fine! Thanks!
